import Head from "next/head";
import dynamic from "next/dynamic";

const Users = dynamic(() => import("users/users"), { ssr: true });

export default function Home({ ...props }) {
  return (
    <>
      <Head>
        <title>Users</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <a>Home</a>
        <Users {...props} />
      </div>
    </>
  );
}

export const getServerSideProps = async (ctx) => {
  const remotePage = await import("users/users");

  if (remotePage.getServerSideProps) {
    return remotePage.getServerSideProps(ctx);
  }

  return {
    props: {},
  };
};
